import web3 from './web3';

const address = '0x5Bf71370674f80a2484945059197Ec6F1D18027F';
const abi = [
  {
     "constant":false,
     "inputs":[
        {
           "name":"name",
           "type":"string"
        },
        {
           "name":"anime",
           "type":"string"
        },
        {
           "name":"avatarUrl",
           "type":"string"
        }
     ],
     "name":"createCharacter",
     "outputs":[

     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"characters",
     "outputs":[
        {
           "name":"name",
           "type":"string"
        },
        {
           "name":"anime",
           "type":"string"
        },
        {
           "name":"avatarUrl",
           "type":"string"
        },
        {
           "name":"value",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"characterId",
           "type":"uint256"
        }
     ],
     "name":"characterOwnership",
     "outputs":[
        {
           "name":"",
           "type":"address"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"getCharactersIds",
     "outputs":[
        {
           "name":"",
           "type":"uint256[]"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":false,
     "inputs":[
        {
           "name":"characterId",
           "type":"uint256"
        }
     ],
     "name":"buyCharacter",
     "outputs":[

     ],
     "payable":true,
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"charactersIds",
     "outputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"characterId",
           "type":"uint256"
        }
     ],
     "name":"getCharacter",
     "outputs":[
        {
           "name":"id",
           "type":"uint256"
        },
        {
           "name":"name",
           "type":"string"
        },
        {
           "name":"anime",
           "type":"string"
        },
        {
           "name":"avatarUrl",
           "type":"string"
        },
        {
           "name":"value",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[

     ],
     "name":"getCharactersLength",
     "outputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "payable":false,
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[

     ],
     "payable":false,
     "stateMutability":"nonpayable",
     "type":"constructor"
  }
];

// exporting local copy of contract that exist in the blockchain
export default new web3.eth.Contract(abi, address);